### PR TITLE
Improved Icon

### PR DESCRIPTION
**Pull request by danielhickman**
Pixel perfect, removed extra anchor points, changed `Normal` shadows to
`Multiply` (whole icon shadow), changed `Multiply` shadows to `Normal`
(glyph shadow), disabled `Align Objects to Pixel Grid`, removed align to
pixel grid on long shadow and tints (causes inaccuracies)

### CODE REVIEW

**Comment by danielhickman** [comment]
P.S. Is the icon free of a license? I would be glad to put this icon under your name at [materialos/Icons](https://github.com/materialos/Icons)

**Comment by plusCubed** [comment]
@danielhickman Oh yeah, feel free to do that. Thanks for the improvements! I do have one question: on the original icon I created a transparency knockout group for the glyph long shadows so that they layer on top of each other but cover the transparency on the layer below. That way the individual shadows were (faintly) distinguishable. Is that OK as a design choice? I see you've merged the individual shadows into one long shadow. I'll add the individual shadows back in if that's allowed.

**Comment by danielhickman** [comment]
Thanks! I've been told by many people that it's not the best looking for Material. Google and the entire KMZ icon pack avoids using it (check Hangouts, it's a good example). I can add it back in, but I think this version is more tasteful.

**Comment by plusCubed** [comment]
Ah, I see. Thanks for your help!

**Comment by danielhickman** [comment]
No problem! Your icon is live on our repo [here](https://github.com/materialos/Icons/commit/174b456f5a5dc3b394e1f7b67b1f23b2d8d9111a).

**Pull request merged**
