### PR TITLE
WIP: Add fdroid build flavor without Crashlytics

### PR DESCRIPTION
**Pull request by schaal**
This adds a new build flavor for fdroid and hides Crashlytics initialization in a wrapper, that only initializes Crashlytics on the gplay build flavor.

I couldn't figure out how to only apply the `io.fabric.tools` gradle plugin for the gplay flavor, but looking at other projects, the approach usually is adding a patch to remove the proprietary dependencies  that is applied before starting the build for F-Droid.

### CODE REVIEW

**Comment by thermatk** [comment]
This is the correct approach, the gradle plugin can be patched out in fdroid metadata with `sed`.
Why wasn't this merged?

**Comment by Catfriend1** [comment]
Please, lgtm.

**Comment by plusCubed** [comment]
@thermatk I'm slowly going through all the documentation on the F-Droid website (there's quite a lot of material...)

I'm also referencing nutritionfactsorg/daily-dozen-android#81 on correctly adhering to the F-Droid inclusion policy, e.g. using `sed` to patch the Crashlytics metadata. 

Do you have any tips/examples in addition to the above? Thanks!

**Comment by thermatk** [comment]
@plusCubed it shouldn't have been that hard and there are some maintainers or me, but seeing you already made the metadata file, the struggle should be over :+1: 

did you check whether it builds? In any case, you may open a merge request with this metadata on fdroiddata (or I may do it if needs be) and get it merged or fixed and merged there

you may surely killoff the overly complicated `init=`, since what is in the android manifest is not important at all. I was surprised to see the same code in referenced issue, but checked in the fdroiddata and it looks easier there:
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.nutritionfacts.dailydozen.txt

**Comment by plusCubed** [comment]
@thermatk Yep, got it working, and deleted the `init=` line. I've opened a merge request: https://gitlab.com/fdroid/fdroiddata/merge_requests/3691

Thanks!

**Pull request merged**
